using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Topzinto.Erp.Application.DTOs.SiteReports;

namespace Topzinto.Erp.Infrastructure.Services;

public static class SiteReportPdfGenerator
{
    private static readonly string Navy = "#1B2B4B";
    private static readonly string Orange = "#F26522";

    static SiteReportPdfGenerator() => QuestPDF.Settings.License = LicenseType.Community;

    public static byte[] Generate(SiteReportDetailDto report)
    {
        return Document.Create(doc =>
        {
            doc.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text("TopZinto CC").Bold().FontSize(18).FontColor(Navy);
                        row.ConstantItem(120).AlignRight().Text("SITE REPORT").Bold().FontColor(Orange);
                    });
                    col.Item().PaddingTop(4).LineHorizontal(2).LineColor(Orange);
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    col.Item().Text(report.ProjectName).Bold().FontSize(14).FontColor(Navy);
                    col.Item().PaddingTop(8).Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.ConstantColumn(120);
                            c.RelativeColumn();
                        });
                        AddRow(table, "Report Date", report.ReportDate);
                        AddRow(table, "Status", report.Status);
                        AddRow(table, "Weather", report.Weather ?? "—");
                        AddRow(table, "Temperature", report.Temperature ?? "—");
                        AddRow(table, "Wind", report.WindSpeed ?? "—");
                        AddRow(table, "Personnel", report.PersonnelCount?.ToString() ?? "—");
                        AddRow(table, "Submitted By", report.SubmittedByName ?? "—");
                    });

                    col.Item().PaddingTop(16).Element(Section("Work Completed", report.WorkCompleted));
                    if (!string.IsNullOrWhiteSpace(report.WorkPlanned))
                        col.Item().PaddingTop(12).Element(Section("Work Planned", report.WorkPlanned));
                    if (!string.IsNullOrWhiteSpace(report.DelaysIssues))
                        col.Item().PaddingTop(12).Element(Section("Delays & Issues", report.DelaysIssues));
                    if (!string.IsNullOrWhiteSpace(report.Notes))
                        col.Item().PaddingTop(12).Element(Section("Notes", report.Notes));
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by TopZinto ERP · ");
                    t.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm")).Italic();
                });
            });
        }).GeneratePdf();
    }

    private static Action<IContainer> Section(string title, string body) => container =>
    {
        container.Column(col =>
        {
            col.Item().Text(title).Bold().FontColor(Navy);
            col.Item().PaddingTop(4).Text(body);
        });
    };

    private static void AddRow(TableDescriptor table, string label, string value)
    {
        table.Cell().PaddingVertical(2).Text(label).SemiBold().FontColor(Colors.Grey.Darken2);
        table.Cell().PaddingVertical(2).Text(value);
    }
}
